//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arco.WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArcoEntities : DbContext
    {
        public ArcoEntities()
            : base("name=ArcoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChooesU> ChooesUs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Number> Numbers { get; set; }
        public virtual DbSet<PackageKey> PackageKeys { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
